name: integracion continua proyecto

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  automatizacion_pruebas:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12   
      - run: npm ci
      - run: npm run test


  flutter:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/app_estudiantes/app_student
    steps:
    
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    
    - uses: subosito/flutter-action@v1
      with:
        channel: 'beta' # 'dev', 'alpha', default to: 'stable'
        flutter-version: '1.12.x' # you can also specify exact version of flutter

    - run: flutter pub get
    - run: flutter format --set-exit-if-changed .
    - run: flutter analyze .
    - run: flutter test

